import{A as q,a as f,S as E,K as k}from"./assets/vendor-3f8040e3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&u(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();q.init({once:!0});function P(e){const r=document.querySelector(e);r&&r.scrollIntoView({behavior:"smooth",block:"start"})}document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(r){r.preventDefault();const o=this.getAttribute("href");P(o)})});const p=document.querySelector(".switch-open-burger"),v=document.querySelector(".switch-close-burger"),T=document.querySelector(".nav-list"),j=document.querySelector(".header-nav"),d=e=>{e.preventDefault(),v.classList.toggle("active-btn"),p.classList.toggle("active-btn"),j.classList.toggle("active-nav")},O=e=>{e.target.getAttribute("class")==="nav-link"&&d(e)};p.addEventListener("click",d);v.addEventListener("click",d);T.addEventListener("click",O);const b=document.querySelector(".theme-btn"),w=document.querySelector(".switch-theme"),A=document.body,y=()=>{A.classList.toggle("dark-theme")},L=()=>{w.classList.toggle("edit-circle")};document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("statusThem")==="true"&&(b.checked=!0,L(),y())});const I=()=>{L(),y();const e=w.classList.length>1;localStorage.setItem("statusThem",e)};b.addEventListener("change",I);document.querySelector(".projects-list");const m=document.querySelectorAll(".projects-item"),_=document.querySelector(".project-btn");_.addEventListener("click",S);let l=0;const B=3;function S(){for(let e=0;e<B;e++){if(l>=m.length){_.style.display="none";break}m[l].classList.remove("is-hidden"),l++}}S();f.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function N(){try{return(await f.get("/reviews")).data}catch{throw new Error("Not found")}}const c=document.querySelector(".reviews__arrow-left"),i=document.querySelector(".reviews__arrow-right"),g=document.querySelector(".reviews__list");async function V(){try{const e=await N();h(e)}catch{h([])}}V();function h(e){if(e.length===0){g.innerHTML="<p>Not found</p>";return}const r=e.map(o=>`<div class="reviews__item swiper-slide">
      <p class="reviews__descr">${o.review}</p>
      <div class="reviews__person">
    
      <img
        width="48"
        class="reviews__img"
        src="${o.avatar_url}"
        alt="${o.author}"
      />
      <h3 class="reviews__h3">${o.author}</h3>
      </div>
    </div>`).join("");g.insertAdjacentHTML("beforeend",r)}const n=new E(".reviews__swiper",{modules:[k],keyboard:{enabled:!0,onlyInViewport:!1},speed:400,spaceBetween:100,breakpoints:{320:{slidesPerView:1,spaceBetween:16},1280:{slidesPerView:2,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:16}}});c.addEventListener("click",()=>{n.slidePrev()});i.addEventListener("click",()=>{n.slideNext()});n.on("fromEdge",()=>{c.classList.remove("disabled_btn"),i.classList.remove("disabled_btn")});n.on("reachBeginning",()=>{c.classList.add("disabled_btn"),i.classList.remove("disabled_btn")});n.on("reachEnd",()=>{i.classList.add("disabled_btn"),c.classList.remove("disabled_btn")});
//# sourceMappingURL=commonHelpers.js.map
